version: '3.7'
services:
  postgres:
    container_name: app_db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "devpass"
    volumes:
      - /var/pg_data:/var/lib/postgresql/data
    networks:
      - task-manager
    ports:
      - "5432:5432"

networks:
  task-manager:
    external: true